channels:
  - conda-forge
dependencies:
  - python=3
  - dask=2.1.0
  - distributed=2.1.0
  - dask-ml=1.0.0
  - dask-labextension>=1.0
  - bokeh
  - ipywidgets
  - jupyterlab>=1.0
  - nbserverproxy
  - nodejs
  - pytables
  - python-graphviz
